import "~/styles/globals.css";
import { Notifications } from '@mantine/notifications';
import '@mantine/core/styles.css';
import '@mantine/notifications/styles.css';
import '@mantine/dates/styles.css';
import 'mantine-datatable/styles.layer.css';

import { type Metadata } from "next";
import { Geist } from "next/font/google";

import { TRPCReactProvider } from "~/trpc/react";
import HeaderBar from "./admin/events/HeaderBar";
import { ThemeProvider } from "./_components/ThemeProvider";
import { ThemeToggle } from "./_components/ThemeToggle";
import { GitHubCorner } from "./_components/GitHubCorner";
import { AIChatFABLazy } from "./_components/AIChatFABLazy";
import { SessionProvider } from "next-auth/react";

export const metadata: Metadata = {
  title: "FtC",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${geist.variable}`}>
      <body>
        <ThemeProvider>
          <SessionProvider>
            <Notifications />
            <TRPCReactProvider>
              <HeaderBar />
              {children}
              <AIChatFABLazy />
              <GitHubCorner />
            </TRPCReactProvider>
            <ThemeToggle />
          </SessionProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
